### PR TITLE
Another set of updates.

### PR DESCRIPTION
**Pull request by imageaid**
Hi, Mike,

I went through to "Numbers" this morning. A couple of typos and a few suggested stylistic enhancements (just like yesterday's edits!). And thanks for the credit offer. I will add my name to the readme in just a moment. Appreciate it!

I'll also do another 45-60 minutes tomorrow morning (headed out for the day today) assuming it's still needed or wanted.

Best,
Craig

### CODE REVIEW

**Comment by mhenke** [comment]
Are you "re-pulling" changes from my repository? Some reason this request won't automatically merge and I'll have to look at it tonight.

**Comment by imageaid** [comment]
Ah, crap! I must have done that. Sorry, Mike. I went to my bookmark, which I believe was to your GitHub repo and not the one I forked. 

Should I re-do it. Really sorry for making that a headache on you! Please let me know if there is something I can change to make it easier on you.

**Comment by mhenke** [comment]
Oh, no problem. I didn't get to merging this last night. It shouldn't be an issue. What every you are doing is fine. Once you get the hang of git, you can follow Bob's Git workflow http://www.silverwareconsulting.com/index.cfm/Git-Workflow

**Comment by imageaid** [comment]
I clearly need to do a review of Git :). Thanks for the link to Bob's workflow!!

**Pull request closed without merging**
