### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by danshort**
Added myself to the contributor list in the readme.

### CODE REVIEW

**Comment by mhenke** [comment]
Dan, i pulled in your changes but you may need to adjust your carriage return setting in your git config. I got a bench of changes. something like autcrf = false; maybe

**Comment by mhenke** [comment]
I think all your changes came across, but you may want to make sure on my fork.

**Comment by danshort** [comment]
I just made the edits directly on github.com by clicking "edit this file". I'll see what I can do by pulling things locally. New to whole git way of doing things.

**Comment by mhenke** [comment]
I might have been mistaken The pull says + 45 additions and - 18 deletions.

**Pull request merged**
