### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by ghost**
changed &lt;br> to  &lt;br /> throughout the document for more consistency ...
changed Arguments.  to arguments for more consistency ...
added 1 space around "=" sign so it's the same in each example.
added links to JJ and Jeremy Allaire on wikipedia.

### CODE REVIEW

**Comment by ghost** [comment]
Just some visual cleanup

**Comment by mhenke** [comment]
These seem fine. Any reason why the pull request was closed?

**Comment by mhenke** [comment]
Looks like the automatic merge so I'll pull these in.

**Comment by ghost** [comment]
I didn't know the request was closed, sorry

**Comment by mhenke** [comment]
no problem all is good. pull and changes look great.

**Pull request merged**
