### PR TITLE
Improper use of "it's".

### PR DESCRIPTION
**Pull request by danshort**

### CODE REVIEW

**Comment by mhenke** [comment]
You may want to do a pull and merge of mhenke:develop. I think the Fork Queue button may do that via github.com since your branch is behind a little. I added a query section if you want to tackle that. thinking it might introduce a query with querynew(). I am probably working on the conditional sections tonight unless someone else does.

**Comment by danshort** [comment]
Yeah, it won't let me apply any of the changes from the Fork Queue. I'll have to do some playing around to figure things out. Always a learning curve with this stuff.

**Comment by mhenke** [comment]
you could delete your repos and refork mine. i have done that a couple times to get caught back up to a repo since the fork queue is flakey sometimes

**Comment by mhenke** [comment]
reopened for awesome merge help information. grabbed it and now closed

**Comment by danshort** [comment]
Yeah, that's what I ended up doing, but I'm sure I'll be in the same boat after the first change I make on github.com where it screws up all my line endings :). I'll get a proper desktop client in the next few days and hopefully be able to start helping again.

**Pull request merged**
